In [1]:
import numpy as np

In [3]:
matriz = np.array([[2, 3, 1], [4, 5, 7]])

In [4]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [16]:
matriz.shape

(2, 3)

In [8]:
matriz[0]

array([2, 3, 1])

In [9]:
matriz[1]

array([4, 5, 7])

In [10]:
matriz[0][0]

2

In [11]:
matriz[1][2]

7

In [13]:
for i in range(matriz.shape[0]):
  print(matriz[i])

[2 3 1]
[4 5 7]


In [18]:
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    print(matriz[i][j])

2
3
1
4
5
7
