# Algoritmos de ordenação
###Eh mais rapido ter um algoritmo nao ordenado e ir inserindo do que inserir num ordenado


In [2]:
import numpy as np

## Bubble sort
###Lento e simples

In [ ]:
def bubble_sort(vetor):
  n = len(vetor)

  for i in range(n):
    for j in range(n-1-i):
      if vetor[j] > vetor[j+1]:
        vetor[j], vetor[j+1] = vetor[j+1], vetor[j]
  return vetor
        

In [ ]:
bubble_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [ ]:
bubble_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Selection sort


In [ ]:
def selection_sort(vetor):
  n = len(vetor)

  for i in range(n):
    menor = i
    for j in range(i+1, n):
      if vetor[menor] > vetor[j]:
        menor = j
    vetor[i], vetor[menor] = vetor[menor], vetor[i]
  
  return vetor

In [ ]:
selection_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [ ]:
selection_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Insertion sort

In [ ]:
def insertion_sort(vetor):
  n = len(vetor)

  for i in range(1, n):
    marcado = vetor[i]
    j = i - 1
    while j >= 0 and marcado < vetor[j]:
      vetor[j + 1] = vetor[j]#vai ir liberando espaco
      j-=1
    vetor[j + 1] = marcado

  return vetor

In [ ]:
insertion_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [ ]:
insertion_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Shell sort

In [ ]:
def shell_sort(vetor):
  intervalo = len(vetor) // 2

  while intervalo > 0:#aqui que eu vou diminuindo o valor dos intervalos
    for i in range(intervalo, len(vetor)):#aqui divide os subvetores
      temp = vetor[i]
      j = i
      while j >= intervalo and vetor[j - intervalo] > temp:#aqui faz os swaps
        vetor[j] = vetor[j - intervalo]
        j -= intervalo
      vetor[j] = temp    
    intervalo //= 2

  return vetor 

In [ ]:
shell_sort(np.array([15, 34, 8, 3]))

2
3
1
2
3


array([15, 34,  8,  3])

In [ ]:
shellSort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 5,  6,  7,  4,  9,  2,  3,  8,  1, 10])

In [ ]:
shell_sort(np.array([8,5,1,4,2,3]))

array([1, 2, 3, 4, 5, 8])

## Merge sort

In [5]:
def merge_sort(vetor):
  if len(vetor) > 1:
    divisao = len(vetor)//2
    esq = vetor[:divisao].copy()
    dir = vetor[divisao:].copy()

    merge_sort(esq)
    merge_sort(dir)

    i = j = k = 0

    #ordena esqueda e direita
    while i < len(esq) and j < len(dir):
      if esq[i] < dir[j]:
        vetor[k] = esq[i]
        i+=1
      else:
        vetor[k] = dir[j]
        j+=1
      k+=1
    
    # Ordenação final
    while i < len(esq):
      vetor[k] = esq[i]
      i += 1
      k += 1
    while j < len(dir):
      vetor[k] = dir[j]
      j += 1
      k += 1
  return vetor



In [ ]:
merge_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [6]:
merge_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
merge_sort(np.array([38, 27, 43, 3, 9, 82, 10]))

array([ 3,  9, 10, 27, 38, 43, 82])

## Quick sort

In [ ]:
def particao(vetor, inicio, final):
  pivo = vetor[final]
  i = inicio - 1

  for j in range(inicio, final):
    if vetor[j] <= pivo:
      i += 1
      vetor[i], vetor[j] = vetor[j], vetor[i]
  vetor[i + 1], vetor[final] = vetor[final], vetor[i + 1]
  return i + 1

def quick_sort(vetor, inicio, final):
  if inicio < final:
    posicao = particao(vetor, inicio, final)
    # Esquerda
    quick_sort(vetor, inicio, posicao - 1)
    # Direito
    quick_sort(vetor, posicao + 1, final)
  return vetor

In [ ]:
vetor = np.array([15, 34, 8, 3])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 3,  8, 15, 34])

In [ ]:
vetor = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Comparativo entre algoritmos

In [ ]:
import random
vetor = []
for _ in range(5000):
  vetor.append(round(random.random(), 4))

In [ ]:
type(vetor)

list

In [ ]:
vetor = np.array(vetor)
type(vetor)

numpy.ndarray

In [ ]:
vetor[:5]

array([0.6102, 0.9907, 0.3947, 0.0478, 0.6364])

In [ ]:
len(vetor)

5000

In [ ]:
%timeit bubble_sort(vetor.copy())

1 loop, best of 3: 6.62 s per loop


In [ ]:
%timeit selection_sort(vetor.copy())

1 loop, best of 3: 3.77 s per loop


In [ ]:
%timeit insertion_sort(vetor.copy())

1 loop, best of 3: 2.67 s per loop


In [ ]:
%timeit shell_sort(vetor.copy())

10 loops, best of 3: 48.7 ms per loop


In [ ]:
%timeit merge_sort(vetor.copy())

10 loops, best of 3: 50 ms per loop


In [ ]:
%timeit quick_sort(vetor.copy(), 0, len(vetor) - 1)

10 loops, best of 3: 30.1 ms per loop


## Vetor ordenado

In [ ]:
class VetorOrdenado:
  
  def __init__(self, capacidade):
    self.capacidade = capacidade
    self.ultima_posicao = -1
    self.valores = np.empty(self.capacidade, dtype=float)

  def insere(self, valor):
    if self.ultima_posicao == self.capacidade - 1:
      print('Capacidade atingida')
      return
    
    posicao = 0
    for i in range(self.ultima_posicao + 1):
      posicao = i
      if self.valores[i] > valor:
        break
      if i == self.ultima_posicao:
        posicao = i + 1

    x = self.ultima_posicao
    while x >= posicao:
      self.valores[x + 1] = self.valores[x]
      x -= 1
    
    self.valores[posicao] = valor    
    self.ultima_posicao += 1

In [ ]:
def insere_ordenado(valores):
  vetor = VetorOrdenado(len(valores))
  for i in range(len(valores)):
    vetor.insere(i)

In [ ]:
%timeit insere_ordenado(vetor.copy())

1 loop, best of 3: 5.37 s per loop
